package com.undertone.udms.logsagg.dto

case class SspFullSchema (  rawid: String,
                            time_stamp: String,
                            request_id: String,
                            user_id: String,
                            publisherid: Int,
                            domain: String,
                            banner_id: Int,
                            variant_id: Int,
                            client_ip_address: String,
                            country: String,
                            user_agent_string: String,
                            referrer_url: String,
                            width: Int,
                            height: Int,
                            score: String,
                            deal_id: String,
                            dsp: String,
                            original_price: Double,
                            bid: Double,
                            advertiser: String,
                            deal_type: String,
                            floor_price: Double,
                            dsp_user_id: String,
                            sever_location: String,
                            auction_type: String,
                            auction_win: Int,
                            result: String,
                            status: String,
                            system: String,
                            no_bid_message: String,
                            dsp_request_id: String,
                            dsp_response_time: String,
                            ttd_id: String,
                            request_type: String,
                            traffic_type: String,
                            device_type: Int,
                            dma: Int,
                            city: String,
                            browser: String,
                            open_market_floor_price: Double,
                            iiq_status_code: Int,
                            dt: String,
                            hash_partition: Int
)



